# Generated by Django 3.2.9 on 2021-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
