# Generated by Django 3.2.9 on 2021-12-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_equipocliente_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='marcar_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='clientes.marca'),
        ),
    ]
