# Generated by Django 3.2.9 on 2021-12-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='categoria_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='clientes.categoria'),
        ),
    ]
