# Generated by Django 3.2.9 on 2021-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_marca_categoria_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='categoria_id',
        ),
    ]
