# Generated by Django 3.2.9 on 2021-12-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20211207_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipocliente',
            name='licencia_equipo',
        ),
    ]
