# Generated by Django 3.2.9 on 2021-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_remove_equipocliente_licencia_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='licencia_equipo',
            field=models.DateField(null=True),
        ),
    ]
