# Generated by Django 3.2.9 on 2021-12-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_equipocliente_licencia_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipocliente',
            name='licencia_equipo',
        ),
    ]
