# Generated by Django 3.2.9 on 2021-12-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_equipocliente_licencia_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipocliente',
            name='acceso_id',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='acceso_lan',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='acceso_wan',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='licencia_equipo',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='equipocliente',
            name='user',
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
    ]
