# Generated by Django 3.2.9 on 2021-12-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20211207_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipocliente',
            name='acceso_id',
        ),
    ]
