# Generated by Django 3.2.9 on 2021-12-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_delete_equipocliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acceso',
        ),
    ]
