# Generated by Django 3.2.9 on 2021-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_contacto_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='licencia_equipo',
            field=models.DateField(),
        ),
    ]
