# Generated by Django 3.2.9 on 2021-12-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_alter_equipo_licencia_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='licencia_equipo',
            field=models.DateTimeField(),
        ),
    ]
