# Generated by Django 3.2.9 on 2021-12-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_equipo_puerto_ssh'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='acceso_id',
            field=models.ForeignKey(blank=True, db_column='acceso_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.acceso'),
        ),
    ]
