# Generated by Django 3.2.9 on 2021-12-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_equipo_acceso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='acceso_id',
            field=models.ForeignKey(blank=True, db_column='acceso_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.acceso', verbose_name='Acceso'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='licencia_equipo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca_id',
            field=models.ForeignKey(db_column='marca_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='clientes.marca', verbose_name='Marca'),
        ),
    ]
